/*
 * generated by Xtext
 */
package budgeting.ui.contentassist

import budgeting.ui.contentassist.AbstractBudgetingProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BudgetingProposalProvider extends AbstractBudgetingProposalProvider {
}
