/*
 * generated by Xtext
 */
package budgeting.ui.outline

import budgeting.budgeting.ActualTransactionEntry
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

class BudgetingOutlineTreeProvider extends DefaultOutlineTreeProvider {
	def protected boolean _isLeaf(ActualTransactionEntry actualTransactionEntry) {
		true
	}
}