/*
 * generated by Xtext
 */
package budgeting.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BudgetingUiModule extends budgeting.ui.AbstractBudgetingUiModule {
	public BudgetingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
