/*
 * generated by Xtext
 */
package budgeting;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BudgetingStandaloneSetup extends BudgetingStandaloneSetupGenerated{

	public static void doSetup() {
		new BudgetingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

