/*
 * generated by Xtext
 */
package budgeting;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.resource.ILocationInFileProvider;

import budgeting.conversion.BudgetingValueConverterService;
import budgeting.resource.BudgetingLocationInFileProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BudgetingRuntimeModule extends budgeting.AbstractBudgetingRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return BudgetingValueConverterService.class;
	}
	
	@Override
	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider() {
		return BudgetingLocationInFileProvider.class;
	}
}