/*
 * generated by Xtext
 */
package budgeting.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import budgeting.services.BudgetingGrammarAccess;

public class BudgetingParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BudgetingGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected budgeting.parser.antlr.internal.InternalBudgetingParser createParser(XtextTokenStream stream) {
		return new budgeting.parser.antlr.internal.InternalBudgetingParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BudgetingFile";
	}
	
	public BudgetingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BudgetingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
