/*
 * generated by Xtext
 */
package budgeting.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import budgeting.ui.internal.BudgetingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BudgetingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BudgetingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BudgetingActivator.getInstance().getInjector(BudgetingActivator.BUDGETING_BUDGETING);
	}
	
}
