/*
 * generated by Xtext
 */
package budgeting;

import org.eclipse.xtext.testing.IInjectorProvider;

import com.google.inject.Injector;

public class BudgetingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return budgeting.ui.internal.BudgetingActivator.getInstance().getInjector("budgeting.Budgeting");
	}

}
